# transaction_types: 
#   - 'send': 
#     - 'CounterpartyID'
#     - 'Amount'
#   - 'receive': 
#     - 'CounterpartyID' 
#     - 'Amount'
#   - 'buyGiftCard': 'Amount'
transaction_types:
  - send
  - recieve
  - buyGiftCard
  - billPay

entity_storage_path: 'data/entity_storage/'
compound_key_templates:
  - FirstName_LastName_Email_Zipcode_PhoneNumber_DriversLicense_Address
  - FirstName_LastName_Email_Zipcode_PhoneNumber_DriversLicense
  - FirstName_LastName_Email_Zipcode_PhoneNumber
  - FirstName_LastName_Email_Zipcode_DriversLicense

potential_columns:
- FirstName
- LastName
- Email
- PhoneNumber
- Zipcode
- DriversLicense
- Address
- DOB
weights:
  Address: 0.2
  DOB: 0.2
  DriversLicense: 0.2
  Email: 0.2
  FirstName: 0.2
  LastName: 0.2
  PhoneNumber: 0.2
  Zipcode: 0.2
threshold: 0.01
